spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e-commerce
    username: root
    password: P@ssw0rd
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
